/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponseDto {

  /**
   * The time in seconds until the token expires
   */
  expiresIn?: number;

  /**
   * The message returned to the user
   */
  message: string;

  /**
   * Indicates whether the request was successful
   */
  success: boolean;

  /**
   * The JWT token for the user
   */
  token?: string;

  /**
   * The ID of the user
   */
  userId: string;
}
