/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {

  /**
   * Whether the user has accepted analytics tracking
   */
  analyticsConsent: boolean;

  /**
   * The email of the user
   */
  email: string;

  /**
   * The password of the user
   */
  password: string;

  /**
   * Whether the user has accepted the privacy policy
   */
  privacyPolicyAccepted: boolean;

  /**
   * Whether the user has accepted the terms of service
   */
  termsAccepted: boolean;

  /**
   * The username of the user
   */
  username: string;
}
